### ISSUE TITLE
KeyError: 'extension' during model_dump() on Pydantic V2 models

### ISSUE THREAD

**Issue by fschreiberclin** [nazrulworld/fhir.resources#185]
When attempting to serialize a FHIR Pydantic model (e.g., Patient) using model_dump() or model_dump_json() in a Pydantic V2 environment, a KeyError: 'extension' occurs if the extension field on the model instance is an empty list [] (or would otherwise be None and excluded).

The traceback points to fhir_core/fhirabstractmodel.py, specifically within the fhir_model_serializer and its _fhir_iter method, where alias_maps['extension'] seems to fail. 
This indicates that the library's custom serializer is attempting to access a key for 'extension' in an internal mapping (alias_maps) which is unexpectedly absent, even when 'extension' is part of the expected element sequence.

This behavior occurs despite:
Ensuring the extension field in the Pydantic model is defined with default_factory=list (e.g., extension: List[Extension] = Field(default_factory=list)), guaranteeing it's always an empty list [] and never None.

Using exclude_none=True or exclude_unset=True in model_dump().

Even explicitly using exclude={'extension'} in model_dump() still results in the same error, reinforcing that the issue lies in the serializer's internal handling of the field's presence rather than its value or explicit exclusion parameters.

**Steps to Reproduce**
1. Define a simple FHIR Pydantic model with an extension field (mimicking fhir.resources.Patient or similar), ensuring extension uses default_factory=list.
```
from typing import List, Optional, Literal, Dict, Any
from pydantic import Field, BaseModel, ValidationError, model_serializer
from collections import OrderedDict

# Assuming fhir.resources.extension.Extension and fhir.resources.fhirtypes.UriType exist
# For a minimal reproducible example without fhir.resources dependency:
class Extension(BaseModel):
    url: str
    valueString: Optional[str] = None

class Patient(BaseModel): # Simplified for reproducibility outside fhir.resources
    resourceType: Literal["Patient"] = Field("Patient", frozen=True)
    id: Optional[str] = None
    name: Optional[List[Dict[str, Any]]] = None

    # This is the problematic field in fhir.resources library's internal serializer
    extension: List[Extension] = Field(default_factory=list) # Ensure it's always a list

    # IMPORTANT: In fhir.resources, there's a custom model_serializer like this.
    # This part is *conceptual* to show where the error is likely happening in their code.
    # You DO NOT define this in YOUR IPS Pydantic models.
    # It's what the fhir_core library's FHIRAbstractModel class *already has*.
    @model_serializer(mode="wrap", when_used="always", return_type=OrderedDict)
    def _custom_fhir_serializer(self, serialize: Any, info: Any) -> OrderedDict:
        # This is a simplified representation of fhir_core/fhirabstractmodel.py's _fhir_iter logic
        data = OrderedDict()
        # This 'elements_sequence' is where 'extension' might be returned
        # but then 'alias_maps' doesn't contain it.
        # In fhir_core, it might look like:
        # for prop_name in self.elements_sequence():
        #     field_key = alias_maps[prop_name] # <-- KeyError likely here if 'extension' is prop_name
        #     value = getattr(self, field_key)
        #     ...

        # For demonstration, let's just make it call the internal Pydantic dump
        # and potentially expose the issue if their wrapped logic is flawed.
        # This is NOT the exact fhir_core code, but simulates its behavior.
        try:
            # This line *itself* is what fhir_core's serializer essentially calls,
            # but fhir_core wraps it with its own problematic logic.
            serialized_data = serialize(self) 
            return OrderedDict(serialized_data)
        except Exception as e:
            raise ValueError(f"Simulated fhir_model_serializer error: {e}")
```

Note: The _custom_fhir_serializer shown above is conceptual and demonstrates where the error is likely occurring in the fhir.resources library's source code (fhir_core/fhirabstractmodel.py). You do not add this _custom_fhir_serializer to your own IPS Pydantic models. Your IPS models simply inherit from fhir.resources models, and the bug lies in how fhir.resources's base FHIRAbstractModel serializes them.

2. Create an instance of the model without explicitly providing extensions (so it defaults to []).

```
patient_instance = Patient(
    id="example-001",
    resourceType="Patient",
    name=[{"family": "Test", "given": ["User"]}]
    # 'extension' will default to an empty list [] due to default_factory
)
```
3. Attempt to dump the model to JSON.

```
# This is the line that causes the error in fhir.resources library
json_output = patient_instance.model_dump_json(indent=2)
print(json_output)

```
**Expected Behavior**
The patient_instance.model_dump_json(indent=2) call should successfully serialize the Patient object into a valid JSON string, with the extension field present as an empty JSON array ("extension": []).

**Actual Behavior**

A PydanticSerializationError is raised, with the root cause being a KeyError: 'extension' originating from fhir_core/fhirabstractmodel.py within the fhir_model_serializer's iteration logic.

```
File ~/projects/clinomic_satellite/satellite-data-platform/.venv/lib/python3.12/site-packages/fhir_core/fhirabstractmodel.py:427, in FHIRAbstractModel.fhir_model_serializer(self, serialize, info)
    421 @model_serializer(mode="wrap", when_used="always", return_type=OrderedDict)
    422 def fhir_model_serializer(
    423     self,
    424     serialize: typing.Callable[[typing.Any], typing.Any],
    425     info: SerializationInfo,
    426 ) -> OrderedDict:
--> 427     return OrderedDict(self._fhir_iter(serialize, info))

File ~/projects/clinomic_satellite/satellite-data-platform/.venv/lib/python3.12/site-packages/fhir_core/fhirabstractmodel.py:440, in FHIRAbstractModel._fhir_iter(self, serialize, info)
    439 for prop_name in self.elements_sequence():
--> 440     field_key = alias_maps[prop_name]
    441     field_info = self.__class__.model_fields[field_key]

KeyError: 'extension'

The above exception was the direct cause of the following exception:

PydanticSerializationError                Traceback (most recent call last)
Cell In[11], line 1
----> 1 print(json.dumps(ips_patient_result.model_dump(by_alias=True, exclude_none=True, exclude={'extension'}), indent=2))

File ~/projects/clinomic_satellite/satellite-data-platform/.venv/lib/python3.12/site-packages/fhir_core/fhirabstractmodel.py:311, in FHIRAbstractModel.model_dump(self, exclude_comments, **pydantic_kwargs)
...
    475         fallback=fallback,
    476         serialize_as_any=serialize_as_any,
    477     )

PydanticSerializationError: Error calling function `fhir_model_serializer`: KeyError: 'extension'
```

**Environment**
Python version: (e.g., Python 3.10, 3.11, 3.12)
pydantic version: (e.g., 2.5.0, 2.6.0, 2.7.0)
fhir.resources version: (e.g., 8.0.0, 8.1.0)
